/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedAuctionsRouteImport } from './routes/_authenticated/auctions'
import { Route as PublicAuctionsAuctionIdRouteImport } from './routes/_public/auctions_.$auctionId'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams_.$teamId'
import { Route as AuthenticatedPlayersImportRouteImport } from './routes/_authenticated/players_.import'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuctionsRoute = AuthenticatedAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicAuctionsAuctionIdRoute = PublicAuctionsAuctionIdRouteImport.update({
  id: '/auctions_/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams_/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersImportRoute =
  AuthenticatedPlayersImportRouteImport.update({
    id: '/players_/import',
    path: '/players/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auctions': typeof AuthenticatedAuctionsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/players/import': typeof AuthenticatedPlayersImportRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/auctions/$auctionId': typeof PublicAuctionsAuctionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auctions': typeof AuthenticatedAuctionsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/players/import': typeof AuthenticatedPlayersImportRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/auctions/$auctionId': typeof PublicAuctionsAuctionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/auctions': typeof AuthenticatedAuctionsRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/players_/import': typeof AuthenticatedPlayersImportRoute
  '/_authenticated/teams_/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_public/auctions_/$auctionId': typeof PublicAuctionsAuctionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auctions'
    | '/players'
    | '/profile'
    | '/teams'
    | '/players/import'
    | '/teams/$teamId'
    | '/auctions/$auctionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auctions'
    | '/players'
    | '/profile'
    | '/teams'
    | '/players/import'
    | '/teams/$teamId'
    | '/auctions/$auctionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/login'
    | '/_authenticated/auctions'
    | '/_authenticated/players'
    | '/_authenticated/profile'
    | '/_authenticated/teams'
    | '/_authenticated/players_/import'
    | '/_authenticated/teams_/$teamId'
    | '/_public/auctions_/$auctionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auctions': {
      id: '/_authenticated/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuthenticatedAuctionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/auctions_/$auctionId': {
      id: '/_public/auctions_/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof PublicAuctionsAuctionIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/teams_/$teamId': {
      id: '/_authenticated/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players_/import': {
      id: '/_authenticated/players_/import'
      path: '/players/import'
      fullPath: '/players/import'
      preLoaderRoute: typeof AuthenticatedPlayersImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuctionsRoute: typeof AuthenticatedAuctionsRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedPlayersImportRoute: typeof AuthenticatedPlayersImportRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuctionsRoute: AuthenticatedAuctionsRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedPlayersImportRoute: AuthenticatedPlayersImportRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAuctionsAuctionIdRoute: typeof PublicAuctionsAuctionIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuctionsAuctionIdRoute: PublicAuctionsAuctionIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
